run_name: "exp_1_basic_unet"
description: "Basic unet run without ransac"
use_wandb: False
wandb_project: "" # put your wandb project name here
dataset_dir: "" # put your dataset directory here
checkpoint_save_path: "chpt" # put here the path to the desirable checkpoint directory

parameters:
  epochs: 15
  device: "cuda:0"
  num_encoder_blocks: 5
  input_channels: 3
  criterion_type: "CrossEntropyLoss"
  max_classes: 2

loader:
  dataset: "kitti"
  batch_size: 4
  workers: 12
  length: 4541
  train_len: 3700
  test_len: 541
  validation_len: 300

other:
  random_seed: 42


